Repository arbron/fvtt-summoner, pull requests merged in 2023-01, with the labels that each got.

#22 D&D 2.1.x causes matchToHit attackBonus failure
  module/summons-actor.mjs
Labels: bug

#25 Multiple summons
  changelog.md
  lang/en.json
  module.json
  module/summon.mjs
  module/summons-item.mjs
  module/summons-type-prompt.mjs
  summoner.css
  templates/summons-section.hbs
Labels: enhancement

#28 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: translation
